[[servers]]
local_address = "1-ff00:0:111,10.1.1.11:10123"
daemon_address = "10.1.1.11:30255"

mbg_reference_clocks = ["/sim/simRefClk"]
ntp_reference_clocks = []
scion_peers = ["1-ff00:0:112,10.1.1.12:10123"]
auth_modes = ["spao"]

ntske_cert_file = "testnet/gen/tls.crt"
ntske_key_file = "testnet/gen/tls.key"
ntske_server_name = "localhost"

dscp = 63

[[servers]]
local_address = "1-ff00:0:112,10.1.1.12:10123"
daemon_address = "10.1.1.12:30255"

mbg_reference_clocks = ["/sim/simRefClk"]
ntp_reference_clocks = []
scion_peers = ["1-ff00:0:111,10.1.1.11:10123"]
auth_modes = ["spao"]

ntske_cert_file = "testnet/gen/tls.crt"
ntske_key_file = "testnet/gen/tls.key"
ntske_server_name = "localhost"

dscp = 63


[[clients]]
local_address = "1-ff00:0:112,10.1.1.12"
remote_address = "1-ff00:0:111,10.1.1.11:10123"