[[servers]]
local_address = "1-ff00:0:111,10.1.1.11"
daemon_address =  "simDaemon11" # empty for now, was "10.1.1.11:30255"

mbg_reference_clocks = []#"simRefClk11"]
ntp_reference_clocks = []
scion_peers = ["1-ff00:0:111,10.1.1.12:10123"]
auth_modes = [] #"spao"]

ntske_cert_file = "testnet/gen/tls.crt"
ntske_key_file = "testnet/gen/tls.key"
ntske_server_name = "localhost"

dscp = 63

random_seed = 11
delay_after_start_seconds = "11s"

[[servers]]
local_address = "1-ff00:0:111,10.1.1.12"
daemon_address = "simDaemon12" # empty for now, was "10.1.1.12:30255"

mbg_reference_clocks = [] # "/sim/simRefClk12"]
ntp_reference_clocks = []
scion_peers = ["1-ff00:0:111,10.1.1.11:10123"]
auth_modes = []#"spao"]

ntske_cert_file = "testnet/gen/tls.crt"
ntske_key_file = "testnet/gen/tls.key"
ntske_server_name = "localhost"

dscp = 63

random_seed = 12
delay_after_start_seconds = "12s"

#[[clients]]
#local_address = "1-ff00:0:111,10.1.1.13"
#daemon_address = "simDaemonClient13" # 10.1.1.11:30255"
#
#ntp_reference_clocks = ["1-ff00:0:111,10.1.1.12:10123"]
#
#dscp = 63
#
#random_seed = 13
#delay_after_start_seconds = "13s"
#
#[[tools]]
#local_address = "1-ff00:0:111,10.1.1.20"
#remote_address = "1-ff00:0:111,10.1.1.11:10123"
#
#random_seed = 20
#delay_after_start_seconds = "20s"