[general]
id = "cs1-ff00_0_110-1"
config_dir = "gen/ASff00_0_110"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/cs1-ff00_0_110-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_110-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_110-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "127.0.0.11:30452"

[features]

[log.console]
level = "debug"

[drkey]
epoch_duration = "30s"
cert_file = "gen/ASff00_0_110/crypto/as/ISD1-ASff00_0_110.pem"
key_file = "gen/ASff00_0_110/crypto/ca/cp-ca.key"
[drkey.drkey_db]
connection = "gen-cache/cs1-ff00_0_110-1.drkey.db"
[drkey.delegation]
piskes = ["127.0.0.11", "10.248.1.1", "10.248.4.1", "127.0.0.12"]
