[general]
id = "co2-ff00_0_211-1"
config_dir = "gen/ASff00_0_211"
reconnect_to_dispatcher = true

[metrics]
prometheus = "10.10.0.186:30457"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[sciond_connection]
address = "10.10.0.188:30255"

[colibri]
delta = 0.3
capacities = "gen/ASff00_0_211/capacities.json"
reservations = "gen/ASff00_0_211/reservations.json"

[log.console]
level = "debug"

[colibri.db]
connection = "gen-cache/co2-ff00_0_211-1.reservation.db"
