[general]
id = "co2-ff00_0_210-1"
config_dir = "gen/ASff00_0_210"
reconnect_to_dispatcher = true

[metrics]
prometheus = "10.10.0.197:30457"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[sciond_connection]
address = "10.10.0.199:30255"

[colibri]
delta = 0.3
capacities = "gen/ASff00_0_210/capacities.json"
reservations = "gen/ASff00_0_210/reservations.json"

[log.console]
level = "debug"

[colibri.db]
connection = "gen-cache/co2-ff00_0_210-1.reservation.db"
