[general]
id = "cs2-ff00_0_210-1"
config_dir = "gen/ASff00_0_210"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/cs2-ff00_0_210-1.trust.db"

[beacon_db]
connection = "gen-cache/cs2-ff00_0_210-1.beacon.db"

[path_db]
connection = "gen-cache/cs2-ff00_0_210-1.path.db"

[drkey]
cert_file = "gen/ASff00_0_210/crypto/as/ISD2-ASff00_0_210.pem"
key_file = "gen/ASff00_0_210/crypto/as/cp-as.key"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.0.0.198:30452"

[api]
addr = "10.0.0.198:31152"

[features]

[ca]
mode = "in-process"

[log.console]
level = "debug"

[drkey.drkey_db]
connection = "gen-cache/cs2-ff00_0_210-1.drkey.db"

[drkey.delegation]
colibri = [ "10.0.0.199",]
piskes = [ "10.0.0.199",]
