[general]
id = "cs2-ff00_0_210-1"
config_dir = "gen/ASff00_0_210"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/cs2-ff00_0_210-1.trust.db"

[beacon_db]
connection = "gen-cache/cs2-ff00_0_210-1.beacon.db"

[path_db]
connection = "gen-cache/cs2-ff00_0_210-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.0.0.198:30452"

[api]
addr = "10.0.0.198:31152"

[features]

[ca]
mode = "in-process"

[log.console]
level = "debug"

[drkey.lvl1_db]
connection = "gen-cache/cs2-ff00_0_210-1.lvl1.db"

[drkey.sv_db]
connection = "gen-cache/cs2-ff00_0_210-1.sv.db"

[drkey.delegation]
colibri = [ "10.0.0.197",]
