[general]
id = "sd2-ff00_0_210"
config_dir = "gen/ASff00_0_210"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/sd2-ff00_0_210.trust.db"

[path_db]
connection = "gen-cache/sd2-ff00_0_210.path.db"

[drkey_db]
connection = "gen-cache/sd2-ff00_0_210.drkey.db"

[sd]
address = "10.0.0.199:30255"
bind_dialer_to_address = true

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.0.0.199:30455"

[features]

[api]
addr = "10.0.0.199:30955"

[log.console]
level = "debug"
