[general]
id = "co1-ff00_0_133-1"
config_dir = "gen/ASff00_0_133"
reconnect_to_dispatcher = true

[metrics]
prometheus = "10.0.0.179:30457"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[sciond_connection]
address = "10.0.0.181:30255"

[colibri]
delta = 0.3
capacities = "gen/ASff00_0_133/capacities.json"
reservations = "gen/ASff00_0_133/reservations.json"

[log.console]
level = "debug"

[colibri.db]
connection = "gen-cache/co1-ff00_0_133-1.reservation.db"
