[general]
id = "sd1-ff00_0_121"
config_dir = "gen/ASff00_0_121"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/sd1-ff00_0_121.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_121.path.db"

[sd]
address = "10.0.0.135:30255"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "10.0.0.135:30455"

[features]

[log.console]
level = "debug"
