[general]
id = "co2-ff00_0_220-1"
config_dir = "gen/ASff00_0_220"
reconnect_to_dispatcher = true

[metrics]
prometheus = "10.0.0.229:30457"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[sciond_connection]
address = "10.0.0.231:30255"

[colibri]
delta = 0.3
capacities = "gen/ASff00_0_220/capacities.json"
reservations = "gen/ASff00_0_220/reservations.json"

[log.console]
level = "debug"

[colibri.db]
connection = "gen-cache/co2-ff00_0_220-1.reservation.db"
